### ISSUE TITLE
mtCloudSim测试HSDC

### ISSUE THREAD

**Issue by ExploreScience** [dscLabJNU/mtCloudSim#2]
您好，我在看《HSDC: A Highly Scalable Data Center Network Architecture for Greater Incremental Scalability》这篇论文模拟实验部分的时候，发现论文中说使用16个端口的交换机构建HSDC。而根据HSDC的性质，网络中应该有1,048,576个服务器，而不是4096个服务器。请问这是怎么回事啊。

**Comment by GitHubDiom** [comment]
您好，论文相关问题请致邮询问相关作者。

**Comment by ExploreScience** [comment]
好的，非常感谢您的建议。
